name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6
        pip install psutil
        pip install pywin32
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name="Pyro RVN Tool" --clean --noupx --disable-windowed-traceback --hidden-import win32api --hidden-import win32con --hidden-import win32gui --hidden-import win32process PyroMacro.py
        
    - name: Zip the executable
      run: |
        Compress-Archive -Path "dist/Pyro RVN Tool.exe" -DestinationPath "dist/Pyro-RVN-Tool.zip"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pyro-RVN-Tool
        path: dist/Pyro-RVN-Tool.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Pyro-RVN-Tool.zip
        name: Pyro RVN Tool ${{ github.ref_name }}
        body: |
          # Pyro RVN Tool ${{ github.ref_name }}

          Basit ve hafif World of Warcraft reklam otomasyon aracı.
          Simple and lightweight World of Warcraft advertisement automation tool.

          ## Özellikler / Features
          - Çoklu client desteği / Multiple client support
          - Özelleştirilebilir tuş atamaları / Customizable key bindings
          - Ayarlanabilir mesaj gecikmesi (30-3600 saniye) / Adjustable message delay (30-3600 seconds)
          - Gerçek zamanlı ilerleme takibi / Real-time progress tracking
          - Otomatik process algılama / Automatic process detection
          - Minimal ve temiz arayüz / Minimal and clean UI
